export default Images = [
    {url: require("./assets/gallery/image(1).jpg")},
    {url: require("./assets/gallery/image(2).jpg")},
    {url: require("./assets/gallery/image(3).jpg")},
    {url: require("./assets/gallery/image(4).jpg")},
    // {url: require("./assets/gallery/image(5).jpg")},
    // {url: require("./assets/gallery/image(6).jpg")},
    // {url: require("./assets/gallery/image(7).jpg")},
    // {url: require("./assets/gallery/image(8).jpg")},
    // {url: require("./assets/gallery/image(9).jpg")},
    // {url: require("./assets/gallery/image(10).jpg")},
    // {url: require("./assets/gallery/image(11).jpg")},
    // {url: require("./assets/gallery/image(12).jpg")},
    // {url: require("./assets/gallery/image(13).jpg")},
    // {url: require("./assets/gallery/image(14).jpg")},
    // {url: require("./assets/gallery/image(15).jpg")},
    // {url: require("./assets/gallery/image(16).jpg")},
    // {url: require("./assets/gallery/image(17).jpg")},
    // {url: require("./assets/gallery/image(18).jpg")},
    // {url: require("./assets/gallery/image(19).jpg")},
    // {url: require("./assets/gallery/image(20).jpg")},
    // {url: require("./assets/gallery/image(21).jpg")},
    // {url: require("./assets/gallery/image(22).jpg")},
    // {url: require("./assets/gallery/image(23).jpg")},
    // {url: require("./assets/gallery/image(24).jpg")},
    // {url: require("./assets/gallery/image(25).jpg")},
    // {url: require("./assets/gallery/image(26).jpg")},
    // {url: require("./assets/gallery/image(27).jpg")},
    // {url: require("./assets/gallery/image(28).jpg")},
    // {url: require("./assets/gallery/image(29).jpg")},
    // {url: require("./assets/gallery/image(30).jpg")},
    // {url: require("./assets/gallery/image(31).jpg")},
    // {url: require("./assets/gallery/image(32).jpg")},
    // {url: require("./assets/gallery/image(33).jpg")},
    // {url: require("./assets/gallery/image(34).jpg")},
    // {url: require("./assets/gallery/image(35).jpg")},
    // {url: require("./assets/gallery/image(36).jpg")},
    // {url: require("./assets/gallery/image(37).jpg")},
    // {url: require("./assets/gallery/image(38).jpg")},
    // {url: require("./assets/gallery/image(39).jpg")},
    // {url: require("./assets/gallery/image(40).jpg")},
    // {url: require("./assets/gallery/image(41).jpg")},
    // {url: require("./assets/gallery/image(42).jpg")},
    // {url: require("./assets/gallery/image(43).jpg")},
    // {url: require("./assets/gallery/image(44).jpg")},
    // {url: require("./assets/gallery/image(45).jpg")},
    // {url: require("./assets/gallery/image(46).jpg")},
    // {url: require("./assets/gallery/image(47).jpg")},
    // {url: require("./assets/gallery/image(48).jpg")}
]
